# ATTN:
# Configure esphome.name & friendly_name
# Configure api.encryption.key
# Configure wifi.manual_ip.static_ip :: 172.16.10.XX

esphome:
  name: kerstboom
  friendly_name: kerstboom

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "WLjG7FBFSudeIk7id20B3jQAyfkVb0Jmc+qxqtHw434="

ota:
  - platform: esphome
    password: "ca4a6b4bafa2d947aa8996746937e9c4"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  manual_ip:
    static_ip: 172.16.10.XX
    gateway: 172.16.10.254
    subnet: 255.255.252.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Itenium2025"
    password: "DenBerg1840!"

captive_portal:

web_server:
  port: 80

switch:
  - platform: gpio
    pin: GPIO0
    name: "stopcontact"
    inverted: False
    restore_mode: ALWAYS_OFF
