# Want to use this?
# Update the api.encryption.key + set a unique wifi.manual_ip.static_ip !!
# (generated during the steps in "ESP Flashing")

esphome:
  name: huisje1
  friendly_name: Huisje1

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "i4MbRmpX9Yv3+HJyhm40UzHQNQDiWqG3XBBu1aCod8A="

ota:
  - platform: esphome
    password: "30cc3f8ae3c629b2f09a7920126b8e55"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  manual_ip:
    static_ip: 192.168.0.123
    gateway: 172.16.10.254
    subnet: 255.255.252.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Itenium2025"
    password: "DenBerg1840!"

captive_portal:

web_server:
  port: 80
