esphome:
  name: huisje1
  friendly_name: Huisje1

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "WLjG7FBFSudeIk7id20B3jQAyfkVb0Jmc+qxqtHw434="

ota:
  - platform: esphome
    password: "ca4a6b4bafa2d947aa8996746937e9c4"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  manual_ip: 
    static_ip: 192.168.0.123
    gateway: 192.168.0.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Huisje1 Fallback Hotspot"
    password: "r1rQQP0Ham3P"

captive_portal:

web_server:
  port: 80

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO16
      mode: INPUT_PULLUP
      inverted: true
    name: "Left Button"

  - platform: gpio
    pin:
      number: GPIO27
      mode: INPUT_PULLUP
      inverted: true
    name: "Right Button"

  - platform: gpio
    pin:
      number: GPIO34
      inverted: false
    name: "Steam"  

  - platform: gpio
    pin:
      number: GPIO14
      inverted: false
    name: "Motion Sensor"
    device_class: motion

  
light:
  - platform: monochromatic
    name: "LED"
    output: led 

  - platform: neopixelbus
    name: "neopixel light"
    variant: SK6812
    type: GRB
    pin: GPIO26
    num_leds: 4
    effects:
      - addressable_random_twinkle:
          name: Random Twinkle Effect With Custom Values
          twinkle_probability: 25%
          progress_interval: 32ms
      - addressable_rainbow:
          name: Rainbow Effect With Custom Values
          speed: 10
          width: 200

output:
  - platform: ledc
    id: led
    pin: GPIO12

  - platform: ledc
    pin: GPIO25
    id: buzzer_output

  - platform: ledc
    id: doors_output
    pin: GPIO13
    frequency: 50 Hz

  - platform: ledc
    id: window_output
    pin: GPIO05
    frequency: 50 Hz
    
  - platform: ledc
    pin: GPIO18
    id: fan_forward
    frequency: 25000 Hz

  - platform: ledc
    pin: GPIO19
    id: fan_reverse
    frequency: 25000 Hz

switch:
  - platform: template
    name: "Buzzer Switch"
    optimistic: true
    turn_on_action:
      - output.turn_on: buzzer_output
      - output.ledc.set_frequency:
          id: buzzer_output
          frequency: 2000Hz  # Adjust frequency as needed
      - output.set_level:
          id: buzzer_output
          level: 15%  # Adjust volume as needed
    turn_off_action:
      - output.turn_off: buzzer_output

sensor:
  - platform: dht
    pin: GPIO17
    model: DHT11
    humidity:
      name: "Roof Humidity"
    temperature:
      name: "Roof Temperature"
    update_interval: 10s

servo:
  - id: window_servo
    output: window_output

  - id: doors_servo
    output: doors_output

number:
  - platform: template
    name: window servo
    min_value: 0
    initial_value: 0
    max_value: 125
    step: 1
    optimistic: true
    on_value:
    - servo.write:
        id: window_servo
        level: !lambda 'return x / 100.0;'


  - platform: template
    name: doors servo
    min_value: -100
    initial_value: 0
    max_value: 100
    step: 1
    optimistic: true
    on_value:
    - servo.write:
        id: doors_servo
        level: !lambda 'return x / 100.0;'

  - platform: template
    name: "Fan Speed"
    min_value: -100
    max_value: 100
    step: 1
    initial_value: 0
    optimistic: true
    set_action:
      then:
        - lambda: |-
            float speed = abs(x) / 100.0;
            if (x > 0) {
              id(fan_forward).set_level(speed);
              id(fan_reverse).set_level(0);
            } else if (x < 0) {
              id(fan_forward).set_level(0);
              id(fan_reverse).set_level(speed);
            } else {
              id(fan_forward).set_level(0);
              id(fan_reverse).set_level(0);
            }